/**
 * Returns a formatted preview of the order-by date derived from
 * required_on_site_date and lead_days.
 *
 * This is a display-only preview. The authoritative order_by_date is
 * GENERATED by Postgres and must never be written by the frontend.
 */
export function getOrderByDatePreview(
  requiredOnSiteDate: string | null,
  leadDays: number | null | undefined
): string | null {
  if (!requiredOnSiteDate) return null
  if (leadDays == null || !Number.isFinite(leadDays)) return null

  const date = new Date(requiredOnSiteDate)
  date.setDate(date.getDate() - leadDays)

  return date.toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
  })
}
